# Testing (H2)
spring:
  datasource:
    url: jdbc:h2://mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa

   # The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    properties:
      hibernate:
    show-sql: true

   #JPA settings
  jpa.hibernate.ddl-auto: update